services:
  mysql-instance:
    container_name: mysql-instance
    image: mysql:8.0.29
    environment:
      MYSQL_DATABASE: rl-fin-flow_db
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: sa
      MYSQL_PASSWORD: password
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 --silent"]
      interval: 10s
      timeout: 50s
      retries: 3
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

  rl-fin-flow-api:
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_USERNAME: sa
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_DATASOURCE_DATABASE: rl-fin-flow_db
      FIRST_USER_USERNAME: bryan
      FIRST_USER_PASSWORD: 4321
    container_name: rl-fin-flow-api
    image: rumenterziev90/rl-fin-flow-api:v1
    restart: on-failure
    depends_on:
      mysql-instance:
        condition: service_healthy
    ports:
      - "8081:8081"
    networks:
      - app-network

  rl-fin-flow-frontend:
    image: rumenterziev90/rl-fin-flow-frontend:v2
    container_name: rl-fin-flow-frontend
    restart: on-failure
    depends_on:
      - rl-fin-flow-api
    ports:
      - "80:80"
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network: