spring.application.name=rl-fin-flow

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.properties.hibernate.format_sql=TRUE
spring.jpa.hibernate.ddl-auto=${DDL_STRATEGY}
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.cloud.gcp.sql.enabled=true
spring.cloud.gcp.sql.instance-connection-name=${CLOUD_SQL_INSTANCE}
spring.cloud.gcp.sql.database-name=${DB_DATABASE}
spring.cloud.gcp.sql.ip-types=PRIVATE

spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.max-lifetime=1800000

spring.jpa.open-in-view=false
server.servlet.session.persistent=false
logging.level.org=WARN
logging.level.blog=WARN
logging.level.org.hibernate.SQL=WARN
logging.level.org.hibernate.type.descriptor=WARN
logging.level.org.hibernate.tool.schema.internal.ExceptionHandlerLoggedImpl=ERROR
logging.level.org.springframework.security=WARN
app.gdpr.policy-version=1
app.cors.allowed-origins=${ALLOWED_ORIGINS}
server.servlet.context-path=/api/v1
springdoc.swagger-ui.path=/swagger-ui
springdoc.swagger-ui.url=/api/v1/v3/api-docs
springdoc.swagger-ui.config-url=/api/v1/v3/api-docs/swagger-config
spring.ai.openai.api-key=${OPEN_AI_API_KEY}
spring.security.oauth2.client.registration.google.redirect-uri=https://rumenterziev.eu/api/v1/login/oauth2/code/google
app.login-redirect-props.redirect-url=${OAUTH2_REDIRECT_URL}
server.servlet.session.cookie.path=/
server.servlet.session.cookie.secure=true
server.servlet.session.cookie.same-site=none
server.forward-headers-strategy=framework
