spring.application.name=rl-fin-flow

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.properties.hibernate.format_sql=TRUE
spring.jpa.hibernate.ddl-auto=${DDL_STRATEGY}

spring.cloud.gcp.sql.enabled=true
spring.cloud.gcp.sql.instance-connection-name=${CLOUD_SQL_INSTANCE}
spring.cloud.gcp.sql.database-name=${DB_DATABASE}
spring.cloud.gcp.sql.ip-types=PRIVATE

spring.jpa.open-in-view=false
server.servlet.session.persistent=false
logging.level.org=WARN
logging.level.blog=WARN
logging.level.org.hibernate.SQL=WARN
logging.level.org.hibernate.type.descriptor=WARN
logging.level.org.hibernate.tool.schema.internal.ExceptionHandlerLoggedImpl=ERROR
logging.level.org.springframework.security=WARN
app.gdpr.policy-version=1
app.cors.allowed-origins=${ALLOWED_ORIGINS}
open.exchange.currency.convertor.url=https://api.currencyapi.com/v3/latest?apikey=cur_live_xC4oXIbGRK4rPBcCm5mBTVEJ2hCrN7iJtt09LapE&currencies=%s&base_currency=%s
server.servlet.context-path=/api/v1
springdoc.swagger-ui.path=/swagger-ui
springdoc.swagger-ui.url=/api/v1/v3/api-docs
springdoc.swagger-ui.config-url=/api/v1/v3/api-docs/swagger-config
spring.ai.openai.api-key=${OPEN_AI_API_KEY}
spring.ai.openai.chat.options.model=gpt-4o
bnb.currency.rate.url=https://www.bnb.bg/Statistics/StExternalSector/StExchangeRates/StERForeignCurrencies/index.htm?download=xml&lang=EN
bnb.currency.rate.euro-fixing=1.95583
spring.security.oauth2.client.registration.google.redirect-uri=https://rumenterziev.eu/api/v1/login/oauth2/code/google
app.login-redirect-props.redirect-url=${OAUTH2_REDIRECT_URL}
server.servlet.session.cookie.path=/
server.servlet.session.cookie.secure=true
server.servlet.session.cookie.same-site=none
server.forward-headers-strategy=framework
