name: Build and Push Docker Images to GHCR

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Gradle and Java
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Build Gradle project
        run: gradle build

      - name: Extract tag version
        id: get_tag
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Docker login to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and Push Docker Images
        run: |
          VERSION_IMAGE="ghcr.io/rumenterziev/dlrfinflow-api:${VERSION}"
          LATEST_IMAGE="ghcr.io/rumenterziev/dlrfinflow-api:latest"
          
          echo "Building Docker image with tags: $VERSION_IMAGE and $LATEST_IMAGE"
          docker build -t "$VERSION_IMAGE" -t "$LATEST_IMAGE" .

          echo "Pushing $VERSION_IMAGE"
          docker push "$VERSION_IMAGE"

          echo "Pushing $LATEST_IMAGE"
          docker push "$LATEST_IMAGE"
